
Inception6
ExploringPriorKnowledge6 
AllowingVenture6
EnlighteningProjection6
ExploringAndResponding6
AncillaryClues6
Closure6
AppraisingVenture6

Inception7
ExploringPriorKnowledge7 
AllowingVenture7
EnlighteningProjection7
ExploringAndResponding7
AncillaryClues7
Closure7
AppraisingVenture7

Inception8
ExploringPriorKnowledge8 
AllowingVenture8
EnlighteningProjection8
ExploringAndResponding8
AncillaryClues8
Closure8
AppraisingVenture8

Inception9
ExploringPriorKnowledge9 
AllowingVenture9
EnlighteningProjection9
ExploringAndResponding9
AncillaryClues9
Closure9
AppraisingVenture9

Inception10
ExploringPriorKnowledge10 
AllowingVenture10
EnlighteningProjection10
ExploringAndResponding10
AncillaryClues10
Closure10
AppraisingVenture10

